# Site settings
title: ZCHuang blog
email: 
description: "Knowing & Doing."
baseurl: ""
url: "http://hzckid.github.io"
github_username:  hzckid

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
